################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

C++M_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CYCLO_FILES := 
OBJDUMP_LIST := 
CCM_DEPS := 
C_UPPER_DEPS := 
S_DEPS := 
CXXM_DEPS := 
C_DEPS := 
CC_DEPS := 
SIZE_OUTPUT := 
C++_DEPS := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
MAP_FILES := 
S_UPPER_DEPS := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Application/User/Core \
Application/User/FATFS/App \
Application/User/FATFS/Target \
Application/User/Startup \
Core/Src \
Drivers/CMSIS/Core/Template/ARMv8-M \
Drivers/CMSIS/Core_A/Source \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/JTest/src \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform/ARMCC \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform/ARMCLANG \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform/GCC \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/basic_math_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/complex_math_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/controller_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/fast_math_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/filtering_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/intrinsics_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/matrix_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/statistics_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/support_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/transform_tests \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/BasicMathFunctions \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/ComplexMathFunctions \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/ControllerFunctions \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/FastMathFunctions \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/FilteringFunctions \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/HelperFunctions \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/Intrinsics \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/MatrixFunctions \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/StatisticsFunctions \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/SupportFunctions \
Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/TransformFunctions \
Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example \
Drivers/CMSIS/DSP/Source/BasicMathFunctions \
Drivers/CMSIS/DSP/Source/CommonTables \
Drivers/CMSIS/DSP/Source/ComplexMathFunctions \
Drivers/CMSIS/DSP/Source/ControllerFunctions \
Drivers/CMSIS/DSP/Source/FastMathFunctions \
Drivers/CMSIS/DSP/Source/FilteringFunctions \
Drivers/CMSIS/DSP/Source/MatrixFunctions \
Drivers/CMSIS/DSP/Source/StatisticsFunctions \
Drivers/CMSIS/DSP/Source/SupportFunctions \
Drivers/CMSIS/DSP/Source/TransformFunctions \
Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/cifar10 \
Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/gru \
Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/Ref_Implementations \
Drivers/CMSIS/NN/NN_Lib_Tests/nn_test \
Drivers/CMSIS/NN/Source/ActivationFunctions \
Drivers/CMSIS/NN/Source/ConvolutionFunctions \
Drivers/CMSIS/NN/Source/FullyConnectedFunctions \
Drivers/CMSIS/NN/Source/NNSupportFunctions \
Drivers/CMSIS/NN/Source/PoolingFunctions \
Drivers/CMSIS/NN/Source/SoftmaxFunctions \
Drivers/CMSIS/RTOS2/Source \
Drivers/CMSIS/RTOS2/Template \
Drivers/CMSIS \
Drivers/STM32F4xx_HAL_Driver/Src \
Drivers/STM32F4xx_HAL_Driver \
FATFS/App \
FATFS/Target \
Middlewares/FatFs \
Middlewares/Third_Party/FatFs/src \
Middlewares/Third_Party/FatFs/src/option \
build \
. \

